CREATE TABLE users_roles (
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    roleId INT NOT NULL,
    userId INT NOT NULL,
    PRIMARY KEY (roleId, userId)
);